### ISSUE TITLE
v2.0.0 Module not found: Can't resolve 'stylis'

### ISSUE THREAD

**Issue by marioil** [styled-components/stylis-plugin-rtl#13]
I updated to v. 2.0.0 and receive this error upon `npm start`:

`./node_modules/stylis-plugin-rtl/dist/stylis-rtl.js`
`Module not found: Can't resolve 'stylis' in '/home/me/Projects/my-project/node_modules/stylis-plugin-rtl/dist'`
`/home/me/Projects/my-project/node_modules/react-scripts/scripts/start.js:19`
`throw err;`
`^`
`Error: ENOENT: no such file or directory, stat "/initrd.img"`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`

Oh and of course thank you for this magical plugin, that's still saving my life!

**Comment by ahmed3hamdan** [comment]
having the same issue when installing version `2.0.0`. not sure why stylis is not being installed even tho it's a peerDependencies for `stylis-plugin-rtl`

**Comment by probablyup** [comment]
peerDependencies are never automatically installed AFAIK, they're a signal that you need to install that package in tandem

**Comment by block2k** [comment]
I have the same issue. How to fix this issue
![image](https://user-images.githubusercontent.com/65883751/194346283-db0209d6-71a1-467a-9b53-6d5728c191d6.png)
