### ISSUE TITLE
2.0.0 Doesn't work

### ISSUE THREAD

**Issue by iassainov** [styled-components/stylis-plugin-rtl#14]
I've just spent 3 hours trying to understand why the plugin stopped working. Reverting to 1.0.0 helped!

**Comment by assainov** [comment]
@probablyup Thanks for such a prompt reply. 
No i didn't. Do you think putting in README will help others?

**Comment by probablyup** [comment]
https://github.com/styled-components/stylis-plugin-rtl/releases/tag/2.0.0

In general it's a good idea to read release notes when you do a major upgrade for any library. I'm sorry you had a hard time here, learning experience!

**Comment by assainov** [comment]
@probablyup actually i installed it in a new repo without paying attention to the release. You will be surprised how many people don't read release notes. anyway, that's why i created this issue.

**Comment by probablyup** [comment]
Added a readme comment https://github.com/styled-components/stylis-plugin-rtl/commit/762e882954771325579edf77308d90d9ac3541f6
