### ISSUE TITLE
There a way to exclude some rule from being changed by the plugin?

### ISSUE THREAD

**Issue by tamir61** [styled-components/stylis-plugin-rtl#15]
Hi, 
I want to exclude CSS file from being manipulated by the stylis-plugin-rtl plugin/StyleSheetManager
There is a way to do it?

Thanks!

**Comment by probablyup** [comment]
Check this out https://github.com/cssjanus/cssjanus#preventing-flipping

**Comment by tamir61** [comment]
I tried that. still doesn't work, it's still changing the direction to rtl

```
/* @noflip */
.stx_yaxis {
  /* y-axis price styles */
  font-size: 12px;
  font-family: Helvetica, sans-serif;
  color: #333;
  background-color: #003eb9;
  direction: ltr !important;
}
```

**Comment by tamir61** [comment]
> Check this out https://github.com/cssjanus/cssjanus#preventing-flipping

I tried that. still doesn't work, it's still changing the direction to rtl

```
/* @noflip */
.stx_yaxis {
  /* y-axis price styles */
  font-size: 12px;
  font-family: Helvetica, sans-serif;
  color: #333;
  background-color: #003eb9;
  direction: ltr !important;
}
```
