### ISSUE TITLE
Typescript issue (Uncaught TypeError: Cannot create property 'return' on number '-1')

### ISSUE THREAD

**Issue by Shaker-Hamdi** [styled-components/stylis-plugin-rtl#18]
I'm using the example in the document, with Next.js like this ...

![Screenshot_1](https://user-images.githubusercontent.com/3071511/96284305-b1cb1e80-0fdd-11eb-810e-b9042e26f264.png)

As you can see, it gives me a typescript error, and on save it gives me this error in the browser ...

![image](https://user-images.githubusercontent.com/3071511/96284439-db844580-0fdd-11eb-9ec2-3d03ed5e08dc.png)

I tried to ignore the types for this package and the typescript error disappeared, however, the error in the browsers still exists.

`(Uncaught TypeError: Cannot create property 'return' on number '-1')`

How can I solve this?

**Comment by Shaker-Hamdi** [comment]
I want to add that this issue only happens in Version 2, when I downgraded to Version 1 it works with no problem.

**Comment by probablyup** [comment]
stylis-plugin-rtl v2 only works with libraries using stylis v4, which at the moment are emotion 11 and the upcoming styled-components v6. This is mentioned in the changelog.
