### ISSUE TITLE
Next.js + Emotion 11 + stylis-plugin-rtl 2

### ISSUE THREAD

**Issue by AliRain** [styled-components/stylis-plugin-rtl#19]
I can't seem to get this to work with Next.js and Emotion 11. I've created a [sandbox](https://codesandbox.io/s/eager-night-zk356).

If you inspect the div, you can see that the `prefixer` plugin correctly prefixed the `display: flex`:
```css
display: -webkit-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
```

However, the RTL plugin did not flip the `padding-left: 50px` to be a `padding-right`.

**Comment by ali-garajian** [comment]
@AliRain I guess this is no longer an issue, since the padding is being flipped correctly when using the `styled` function.
