### ISSUE TITLE
Invalid types for v2.0.1

### ISSUE THREAD

**Issue by arobert93** [styled-components/stylis-plugin-rtl#23]
Hi there,

Could you please update the types (TS) to match v2.0.1? Currently it exports the wrong types from v1.

Edit:
@emotion/cache (v11) **createCache** plugins list expects these types:

```ts
export type StylisPlugin = (
  element: StylisElement,
  index: number,
  children: Array<StylisElement>,
  callback: StylisPluginCallback
) => string | undefined
```

Thank you,
Alexandru

**Comment by probablyup** [comment]
Would you be open to submitting a PR?

**Comment by probablyup** [comment]
Emotion's types are wrong then... I'm directly using the types from `stylis`
